name: üõ†Ô∏è Revisi√≥n obligatoria

on:
  pull_request:

jobs:
  recordatorio:
    name: ‚ö†Ô∏è  RECUERDA Debes actualizar los cambios en todos los servidores
    runs-on: ubuntu-latest
    steps:
      - name: üü° Actualizar servidores
        run: |
          echo ""
          echo -e "\033[1;33m‚ö†Ô∏è  RECUERDA: Debes actualizar los cambios en todos los servidores.\033[0m"
          echo ""
